"""
Adapter for sebokep.com
Auto-generated by AdapterScout
"""

from typing import Optional
from .. import BaseAdapter, AdapterRegistry


@AdapterRegistry.register
class SebokepComAdapter(BaseAdapter):
    """Adapter for sebokep.com."""

    DOMAINS = ["sebokep.com", "www.sebokep.com"]
    STREAM_TYPES = ['HLS', 'TS_SEGMENT']

    async def before_scrape(self) -> None:
        """Prepare page — dismiss ads, click play."""
        await self.page.wait_for_timeout(2000)

        # Start playback
        await self._safe_click("[class*='play']")
        await self.page.wait_for_timeout(3000)

    async def extract_title(self) -> Optional[str]:
        el = await self.page.query_selector("meta[property='og:title']")
        if el:
            return await el.get_attribute("content")
        return await self.page.title()

    # ── helpers ──

    async def _safe_click(self, selector: str) -> bool:
        """Click element if visible."""
        try:
            el = await self.page.query_selector(selector)
            if el and await el.is_visible():
                await el.click()
                return True
        except Exception:
            pass
        return False

    async def _safe_remove(self, selector: str) -> None:
        """Remove matching elements from DOM."""
        try:
            await self.page.evaluate(
                "(sel) => document.querySelectorAll(sel)"
                ".forEach(e => e.remove())",
                selector,
            )
        except Exception:
            pass