"""Adapter for bokepindo.to. Auto-generated by CSVScout v3."""

from typing import List, Dict
from .. import BaseAdapter, AdapterRegistry


@AdapterRegistry.register
class BokepindoToAdapter(BaseAdapter):
    """Adapter for bokepindo.to."""

    DOMAINS = ["bokepindo.to", "www.bokepindo.to"]

    CONTAINER_SELECTOR  = ".videos-list article"
    TITLE_SELECTOR      = "span.title"
    LINK_SELECTOR       = "a[href]"
    THUMBNAIL_SELECTOR  = "img.video-main-thumb"
    DURATION_SELECTOR   = "div.post-thumbnail"
    VIEWS_SELECTOR      = "div.under-thumb"

    PAGINATION_TYPE = "numbered"
    PAGINATION_SELECTOR = "#page a"


    async def extract_videos(self, page) -> List[Dict]:
        """Extract video list from current page."""
        return await page.evaluate(
            """(s) => {
                const results = [];
                document.querySelectorAll(s.container).forEach(item => {
                    const t = item.querySelector(s.title);
                    const l = item.querySelector(s.link);
                    const i = item.querySelector(s.thumbnail);
                    const d = item.querySelector(s.duration);
                    const v = item.querySelector(s.views);
                    if (t || l) results.push({
                        title: t ? t.textContent.trim() : '',
                        link: l ? l.href : '',
                        thumbnail: i ? (i.src || i.dataset.src || '') : '',
                        duration: d ? d.textContent.trim() : '',
                        views: v ? v.textContent.trim() : '',
                    });
                });
                return results;
            }""",
            {
                "container": self.CONTAINER_SELECTOR,
                "title":     self.TITLE_SELECTOR,
                "link":      self.LINK_SELECTOR,
                "thumbnail": self.THUMBNAIL_SELECTOR,
                "duration":  self.DURATION_SELECTOR,
                "views":     self.VIEWS_SELECTOR,
            },
        )
