"""Adapter for dicrotin.com. Auto-generated by CSVScout."""

from typing import List, Dict
from .. import BaseAdapter, AdapterRegistry


@AdapterRegistry.register
class DicrotinComAdapter(BaseAdapter):
    """Adapter for dicrotin.com."""

    DOMAINS = ["dicrotin.com", "www.dicrotin.com"]

    CONTAINER_SELECTOR  = "div.row.no-gutters > div.col-12.col-md-4.col-lg-3.col-xl-2"
    TITLE_SELECTOR      = "span.title"
    LINK_SELECTOR       = "a.thumb"
    THUMBNAIL_SELECTOR  = "img.video-img.img-fluid.loaded"
    DURATION_SELECTOR   = "a.thumb"
    VIEWS_SELECTOR      = "div.video-datas"
    PAGINATION_SELECTOR = ".page-item a.page-link"

    async def extract_videos(self, page) -> List[Dict]:
        """Extract video list."""
        return await page.evaluate(
            """(s) => {
                const results = [];
                document.querySelectorAll(s.container).forEach(item => {
                    const t = item.querySelector(s.title);
                    const l = item.querySelector(s.link);
                    const i = item.querySelector(s.thumbnail);
                    const d = item.querySelector(s.duration);
                    const v = item.querySelector(s.views);
                    if (t || l) results.push({
                        title: t ? t.textContent.trim() : '',
                        link: l ? l.href : '',
                        thumbnail: i ? (i.src || i.dataset.src || '') : '',
                        duration: d ? d.textContent.trim() : '',
                        views: v ? v.textContent.trim() : '',
                    });
                });
                return results;
            }""",
            {
                "container": self.CONTAINER_SELECTOR,
                "title":     self.TITLE_SELECTOR,
                "link":      self.LINK_SELECTOR,
                "thumbnail": self.THUMBNAIL_SELECTOR,
                "duration":  self.DURATION_SELECTOR,
                "views":     self.VIEWS_SELECTOR,
            },
        )
