"""Adapter for jable.tv. Auto-generated by CSVScout v3."""

from typing import List, Dict
from .. import BaseAdapter, AdapterRegistry


@AdapterRegistry.register
class JableTvAdapter(BaseAdapter):
    """Adapter for jable.tv."""

    DOMAINS = ["jable.tv", "www.jable.tv"]

    CONTAINER_SELECTOR  = "div.row.gutter-20 > div.col-6.col-sm-4.col-lg-3"
    TITLE_SELECTOR      = "a.h5.text-light"
    LINK_SELECTOR       = "a.h5.text-light"
    THUMBNAIL_SELECTOR  = "img[data-src]"
    DURATION_SELECTOR   = ".duration"
    VIEWS_SELECTOR      = ".views"

    PAGINATION_TYPE = "next_button"
    NEXT_BUTTON_SELECTOR = "button.owl-next"

    async def go_next_page(self, page):
        """Click the Next button."""
        btn = page.locator(self.NEXT_BUTTON_SELECTOR)
        if await btn.count() > 0 and await btn.first.is_visible():
            await btn.first.click()
            await page.wait_for_load_state("domcontentloaded")
            return True
        return False


    async def extract_videos(self, page) -> List[Dict]:
        """Extract video list from current page."""
        return await page.evaluate(
            """(s) => {
                const results = [];
                document.querySelectorAll(s.container).forEach(item => {
                    const t = item.querySelector(s.title);
                    const l = item.querySelector(s.link);
                    const i = item.querySelector(s.thumbnail);
                    const d = item.querySelector(s.duration);
                    const v = item.querySelector(s.views);
                    if (t || l) results.push({
                        title: t ? t.textContent.trim() : '',
                        link: l ? l.href : '',
                        thumbnail: i ? (i.src || i.dataset.src || '') : '',
                        duration: d ? d.textContent.trim() : '',
                        views: v ? v.textContent.trim() : '',
                    });
                });
                return results;
            }""",
            {
                "container": self.CONTAINER_SELECTOR,
                "title":     self.TITLE_SELECTOR,
                "link":      self.LINK_SELECTOR,
                "thumbnail": self.THUMBNAIL_SELECTOR,
                "duration":  self.DURATION_SELECTOR,
                "views":     self.VIEWS_SELECTOR,
            },
        )
