"""
CSV Getter v3 — Reads adapter files generated by Scout, scrapes to CSV/{domain}.csv

Flow:
  1. User gives URL
  2. Getter looks for adapter in csv_getter/adapters/domains/{domain}.py
  3. If not found → run Scout automatically → save adapter
  4. Load adapter → read selectors → scrape → save CSV/{domain}.csv
"""

import csv
import asyncio
import importlib
import importlib.util
import inspect
import logging
import random
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Any
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse

from playwright.async_api import (
    async_playwright,
    Page,
    Browser,
    BrowserContext,
    Playwright,
)

logger = logging.getLogger(__name__)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Constants
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BROWSER_ARGS = [
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-blink-features=AutomationControlled",
    "--disable-web-security",
    "--disable-dev-shm-usage",
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
]

STEALTH_JS = """
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
window.chrome = { runtime: {} };
Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
"""

CSV_FOLDER = Path("CSV")
ADAPTERS_FOLDER = Path("csv_getter/adapters/domains")

DEFAULT_CONCURRENT = 7


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Adapter Loader
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _domain_to_slug(domain: str) -> str:
    """jable.tv → jable_tv"""
    return re.sub(r"[^a-zA-Z0-9]", "_", domain.replace("www.", ""))


def _url_to_domain(url: str) -> str:
    """https://www.jable.tv/categories/... → jable.tv"""
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    return urlparse(url).netloc.replace("www.", "")


def find_adapter_file(domain: str) -> Optional[Path]:
    """Find adapter .py file for domain."""
    slug = _domain_to_slug(domain)
    path = ADAPTERS_FOLDER / f"{slug}.py"
    if path.exists():
        return path
    # Also try with www
    slug_www = _domain_to_slug("www." + domain)
    path_www = ADAPTERS_FOLDER / f"{slug_www}.py"
    if path_www.exists():
        return path_www
    return None


def load_adapter_class(filepath: Path) -> Optional[Dict]:
    """
    Parse adapter .py file via regex.
    Simple and reliable — no dynamic import needed.
    """
    return _parse_adapter_text(filepath)


def _patch_adapter_imports(module_name: str):
    """
    Create dummy base classes so adapter files can be imported
    without the full package structure.
    """
    # Create fake parent package
    class DummyBaseAdapter:
        pass
    
    class DummyRegistry:
        @staticmethod
        def register(cls):
            return cls
    
    # Fake modules
    parent_name = module_name.rsplit(".", 1)[0] if "." in module_name else "csv_getter_adapters"
    
    class FakeModule:
        BaseAdapter = DummyBaseAdapter
        AdapterRegistry = DummyRegistry
    
    # Register in sys.modules so "from .. import" resolves
    sys.modules.setdefault("csv_getter", FakeModule())
    sys.modules.setdefault("csv_getter.adapters", FakeModule())
    sys.modules.setdefault("csv_getter.adapters.domains", FakeModule())


def _parse_adapter_text(filepath: Path) -> Optional[Dict]:
    """
    Parse adapter .py as text to extract selectors.
    Handles quotes inside selectors like [class*='thumb']
    """
    text = filepath.read_text(encoding="utf-8")
    selectors = {}

    fields = {
        "container":    "CONTAINER_SELECTOR",
        "title":        "TITLE_SELECTOR",
        "link":         "LINK_SELECTOR",
        "thumbnail":    "THUMBNAIL_SELECTOR",
        "duration":     "DURATION_SELECTOR",
        "views":        "VIEWS_SELECTOR",
        "pag_type":     "PAGINATION_TYPE",
        "pag_selector": "PAGINATION_SELECTOR",
        "next_btn":     "NEXT_BUTTON_SELECTOR",
        "loadmore":     "LOAD_MORE_SELECTOR",
        "sentinel":     "SENTINEL_SELECTOR",
        "page_param":   "PAGE_PARAM",
        "api_endpoint": "API_ENDPOINT",
    }

    for key, attr in fields.items():
        # Try double quotes first (handles single quotes inside)
        #   THUMBNAIL_SELECTOR = "[class*='thumb'] img"
        #                         ^^^^^^^^^^^^^^^^^^^^^ captured
        pattern_dq = attr + r'\s*=\s*"([^"]*)"'
        match = re.search(pattern_dq, text)

        if not match:
            # Then try single quotes (handles double quotes inside)
            pattern_sq = attr + r"\s*=\s*'([^']*)'"
            match = re.search(pattern_sq, text)

        if match:
            selectors[key] = match.group(1)

    # Domain
    domain_match = re.search(r'DOMAINS\s*=\s*\[(.+?)\]', text)
    if domain_match:
        domains = re.findall(r'["\']([^"\']+)["\']', domain_match.group(1))
        selectors["domains"] = domains

    if selectors.get("container"):
        return selectors

    return None

def _adapter_to_config(adapter, base_url: str) -> "SiteConfig":
    """Convert loaded adapter (class or dict) to SiteConfig."""
    
    if isinstance(adapter, dict):
        # From text parsing
        d = adapter
        domain = d.get("domains", [""])[0] if d.get("domains") else _url_to_domain(base_url)
        
        return SiteConfig(
            base_url=base_url,
            domain=domain,
            container=d.get("container", "article"),
            title=d.get("title", ".title"),
            link=d.get("link", "a"),
            thumbnail=d.get("thumbnail", "img"),
            duration=d.get("duration", ".duration"),
            views=d.get("views", ".views"),
            pagination_type=d.get("pag_type", "numbered"),
            pagination_selector=d.get("pag_selector", ".pagination a"),
            next_button_selector=d.get("next_btn", ""),
            load_more_selector=d.get("loadmore", ""),
            sentinel_selector=d.get("sentinel", ""),
            page_param=d.get("page_param", "page"),
            api_endpoint=d.get("api_endpoint", ""),
        )
    
    # From class
    cls = adapter
    domain = ""
    if hasattr(cls, "DOMAINS") and cls.DOMAINS:
        domain = cls.DOMAINS[0]
    if not domain:
        domain = _url_to_domain(base_url)
    
    pag_type = getattr(cls, "PAGINATION_TYPE", "numbered")
    
    return SiteConfig(
        base_url=base_url,
        domain=domain,
        container=getattr(cls, "CONTAINER_SELECTOR", "article"),
        title=getattr(cls, "TITLE_SELECTOR", ".title"),
        link=getattr(cls, "LINK_SELECTOR", "a"),
        thumbnail=getattr(cls, "THUMBNAIL_SELECTOR", "img"),
        duration=getattr(cls, "DURATION_SELECTOR", ".duration"),
        views=getattr(cls, "VIEWS_SELECTOR", ".views"),
        pagination_type=pag_type,
        pagination_selector=getattr(cls, "PAGINATION_SELECTOR", ".pagination a"),
        next_button_selector=getattr(cls, "NEXT_BUTTON_SELECTOR", ""),
        load_more_selector=getattr(cls, "LOAD_MORE_SELECTOR", ""),
        sentinel_selector=getattr(cls, "SENTINEL_SELECTOR", ""),
        page_param=getattr(cls, "PAGE_PARAM", "page"),
        api_endpoint=getattr(cls, "API_ENDPOINT", ""),
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  SiteConfig
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class SiteConfig:
    """All config needed to scrape one site."""
    
    def __init__(
        self,
        base_url: str,
        domain: str = "",
        container: str = "article",
        title: str = ".title",
        link: str = "a",
        thumbnail: str = "img",
        duration: str = ".duration",
        views: str = ".views",
        pagination_type: str = "numbered",
        pagination_selector: str = ".pagination a",
        next_button_selector: str = "",
        load_more_selector: str = "",
        sentinel_selector: str = "",
        page_param: str = "page",
        page_in_path: bool = True,
        api_endpoint: str = "",
        concurrent: int = DEFAULT_CONCURRENT,
        max_pages: int = 0,
    ):
        self.base_url = base_url
        self.domain = domain or _url_to_domain(base_url)
        self.container = container
        self.title = title
        self.link = link
        self.thumbnail = thumbnail
        self.duration = duration
        self.views = views
        self.pagination_type = pagination_type
        self.pagination_selector = pagination_selector
        self.next_button_selector = next_button_selector
        self.load_more_selector = load_more_selector
        self.sentinel_selector = sentinel_selector
        self.page_param = page_param
        self.page_in_path = page_in_path
        self.api_endpoint = api_endpoint
        self.concurrent = concurrent
        self.max_pages = max_pages
    
    @property
    def domain_slug(self) -> str:
        return _domain_to_slug(self.domain)
    
    @property
    def csv_path(self) -> Path:
        return CSV_FOLDER / f"{self.domain_slug}.csv"
    
    @property
    def csv_temp_path(self) -> Path:
        return CSV_FOLDER / f"{self.domain_slug}_temp.csv"
    
    @classmethod
    def from_adapter_file(cls, filepath: Path, base_url: str) -> "SiteConfig":
        """Load config from saved adapter .py file."""
        adapter = load_adapter_class(filepath)
        if adapter is None:
            adapter = _parse_adapter_text(filepath)
        if adapter is None:
            raise ValueError(f"Cannot parse adapter file: {filepath}")
        return _adapter_to_config(adapter, base_url)
    
    @classmethod
    def from_url(cls, url: str) -> Optional["SiteConfig"]:
        """
        Try to find existing adapter file for this URL's domain.
        Returns None if no adapter found.
        """
        domain = _url_to_domain(url)
        filepath = find_adapter_file(domain)
        if filepath:
            return cls.from_adapter_file(filepath, url)
        return None
    
    def print_summary(self):
        """Print config summary."""
        print(f"   Domain:      {self.domain}")
        print(f"   URL:         {self.base_url}")
        print(f"   Container:   {self.container}")
        print(f"   Title:       {self.title}")
        print(f"   Link:        {self.link}")
        print(f"   Thumbnail:   {self.thumbnail}")
        print(f"   Duration:    {self.duration}")
        print(f"   Views:       {self.views}")
        print(f"   Pagination:  {self.pagination_type}")
        if self.pagination_type == "next_button":
            print(f"   Next btn:    {self.next_button_selector}")
        elif self.pagination_type == "load_more":
            print(f"   Load more:   {self.load_more_selector}")
        elif self.pagination_type == "infinite_scroll":
            print(f"   Sentinel:    {self.sentinel_selector}")
        else:
            print(f"   Pag select:  {self.pagination_selector}")
        print(f"   Output:      {self.csv_path}")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  CSVGetter
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class CSVGetter:
    """
    Scrape video listings to CSV/{domain}.csv
    
    Uses adapter files saved by Scout for selectors.
    """
    
    def __init__(self, config: SiteConfig):
        self.config = config
        self._playwright: Optional[Playwright] = None
        self._browser: Optional[Browser] = None
        self._context: Optional[BrowserContext] = None
        self._all_data: List[Dict] = []
        self._seen_links: set = set()
    
    async def __aenter__(self):
        await self._start()
        return self
    
    async def __aexit__(self, *args):
        await self._close()
    
    async def _start(self):
        CSV_FOLDER.mkdir(parents=True, exist_ok=True)
        self._playwright = await async_playwright().start()
        self._browser = await self._playwright.chromium.launch(
            headless=True, args=BROWSER_ARGS,
        )
        self._context = await self._browser.new_context(
            user_agent=random.choice(USER_AGENTS),
            viewport={"width": 1920, "height": 1080},
            locale="en-US",
            bypass_csp=True,
            ignore_https_errors=True,
        )
        await self._context.add_init_script(STEALTH_JS)
    
    async def _close(self):
        if self._browser:
            await self._browser.close()
        if self._playwright:
            await self._playwright.stop()
    
    # ── URL builder ──
    
    def _build_page_url(self, page_num: int) -> str:
        base = self.config.base_url.rstrip("/")
        cfg = self.config
        
        if page_num <= 1:
            return base + "/"
        
        if cfg.page_in_path:
            clean = re.sub(r"/page/\d+/?$", "", base)
            return f"{clean}/page/{page_num}/"
        else:
            parsed = urlparse(base)
            params = parse_qs(parsed.query)
            params[cfg.page_param] = [str(page_num)]
            return urlunparse(parsed._replace(
                query=urlencode(params, doseq=True)
            ))
    
    # ── Extract ──
    
    async def _extract_from_page(self, page: Page) -> List[Dict]:
        cfg = self.config
        return await page.evaluate(
            """(s) => {
                const results = [];
                document.querySelectorAll(s.container).forEach(item => {
                    const t = item.querySelector(s.title);
                    const l = item.querySelector(s.link);
                    const i = item.querySelector(s.thumbnail);
                    const d = item.querySelector(s.duration);
                    const v = item.querySelector(s.views);
                    
                    const title = t ? t.textContent.trim()
                                    : (l ? l.textContent.trim() : '');
                    const link = l ? (l.href || l.getAttribute('data-href') || '') : '';
                    const thumbnail = i
                        ? (i.src || i.getAttribute('data-src')
                           || i.getAttribute('data-lazy-src')
                           || i.getAttribute('data-original') || '')
                        : '';
                    const duration = d ? d.textContent.trim() : '';
                    const views = v ? v.textContent.trim() : '';
                    
                    if (title || link) {
                        results.push({ title, link, thumbnail, duration, views });
                    }
                });
                return results;
            }""",
            {
                "container": cfg.container,
                "title":     cfg.title,
                "link":      cfg.link,
                "thumbnail": cfg.thumbnail,
                "duration":  cfg.duration,
                "views":     cfg.views,
            },
        )
    
    # ── Scroll ──
    
    async def _scroll_down(self, page: Page, times: int = 3):
        for _ in range(times):
            await page.evaluate(
                f"window.scrollBy(0, {random.randint(400, 900)})"
            )
            await asyncio.sleep(0.8 + random.random() * 0.5)
        await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
        await asyncio.sleep(1)
    
    # ── Dedup ──
    
    def _dedup(self, data: List[Dict]) -> List[Dict]:
        new_items = []
        for item in data:
            link = item.get("link", "")
            if link and link not in self._seen_links:
                self._seen_links.add(link)
                new_items.append(item)
            elif not link:
                title = item.get("title", "")
                key = f"__t__{title}"
                if title and key not in self._seen_links:
                    self._seen_links.add(key)
                    new_items.append(item)
        return new_items
    
    # ── Detect total pages ──
    
    async def _detect_total_pages(self) -> int:
        cfg = self.config
        
        if cfg.pagination_type in ("load_more", "infinite_scroll"):
            return 0
        
        page = await self._context.new_page()
        try:
            url = self._build_page_url(1)
            await page.goto(url, wait_until="domcontentloaded", timeout=45_000)
            await asyncio.sleep(2)
            
            total = await page.evaluate(
                """(pagSel) => {
                    let max = 1;
                    const links = document.querySelectorAll(pagSel);
                    links.forEach(a => {
                        const hm = (a.href||'').match(/\\/page\\/(\\d+)/);
                        if (hm) max = Math.max(max, parseInt(hm[1]));
                        const qm = (a.href||'').match(/[?&]page=(\\d+)/);
                        if (qm) max = Math.max(max, parseInt(qm[1]));
                        const text = a.textContent.trim();
                        if (/^\\d+$/.test(text)) max = Math.max(max, parseInt(text));
                    });
                    // "Page X of Y"
                    const ofM = document.body.innerText.match(/page\\s+\\d+\\s+of\\s+(\\d+)/i);
                    if (ofM) max = Math.max(max, parseInt(ofM[1]));
                    // data attributes
                    const dEl = document.querySelector('[data-total-pages],[data-last-page]');
                    if (dEl) {
                        const v = dEl.getAttribute('data-total-pages') || dEl.getAttribute('data-last-page');
                        if (v && /^\\d+$/.test(v)) max = Math.max(max, parseInt(v));
                    }
                    return max;
                }""",
                cfg.pagination_selector,
            )
            return total or 1
        except Exception as exc:
            logger.warning(f"⚠️ Can't detect pages: {exc}")
            return 1
        finally:
            await page.close()
    
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    #  Scrape Strategies
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    async def _scrape_single_page(self, page_num: int) -> Tuple[int, List[Dict]]:
        page = await self._context.new_page()
        try:
            url = self._build_page_url(page_num)
            resp = await page.goto(url, wait_until="domcontentloaded", timeout=45_000)
            if resp and resp.status >= 400:
                logger.warning(f"   ❌ Page {page_num}: HTTP {resp.status}")
                return (page_num, [])
            await asyncio.sleep(1.5 + random.random())
            await self._scroll_down(page, times=2)
            data = await self._extract_from_page(page)
            for item in data:
                item["page"] = page_num
            logger.info(f"   ✅ Page {page_num}: {len(data)} videos")
            return (page_num, data)
        except Exception as exc:
            logger.warning(f"   ❌ Page {page_num}: {str(exc)[:60]}")
            return (page_num, [])
        finally:
            await page.close()
    
    async def _scrape_numbered(self, total_pages: int) -> List[Dict]:
        all_data: List[Dict] = []
        concurrent = self.config.concurrent
        
        for batch_start in range(1, total_pages + 1, concurrent):
            batch_end = min(batch_start + concurrent, total_pages + 1)
            pages = list(range(batch_start, batch_end))
            logger.info(f"📦 Batch: pages {batch_start}–{batch_end - 1}")
            
            tasks = [self._scrape_single_page(pg) for pg in pages]
            results = await asyncio.gather(*tasks)
            
            for _, data in results:
                new = self._dedup(data)
                all_data.extend(new)
            
            if all_data:
                self._save_csv(all_data, temp=True)
            
            await asyncio.sleep(1.5 + random.random())
        
        return all_data
    
    async def _scrape_click_next(self) -> List[Dict]:
        cfg = self.config
        selector = cfg.next_button_selector or cfg.pagination_selector
        all_data: List[Dict] = []
        page_num = 0
        max_pages = cfg.max_pages or 500
        
        page = await self._context.new_page()
        try:
            await page.goto(
                self._build_page_url(1),
                wait_until="domcontentloaded", timeout=45_000,
            )
            await asyncio.sleep(2)
            
            while page_num < max_pages:
                page_num += 1
                await self._scroll_down(page, times=2)
                
                data = await self._extract_from_page(page)
                for item in data:
                    item["page"] = page_num
                
                new = self._dedup(data)
                all_data.extend(new)
                logger.info(f"   ✅ Page {page_num}: {len(new)} new videos (total {len(all_data)})")
                
                if new:
                    self._save_csv(all_data, temp=True)
                
                btn = page.locator(selector).first
                try:
                    if await btn.count() == 0 or not await btn.is_visible():
                        logger.info("   🏁 No more 'Next' button — done")
                        break
                    await btn.click()
                    await page.wait_for_load_state("domcontentloaded", timeout=30_000)
                    await asyncio.sleep(2 + random.random())
                except Exception:
                    logger.info("   🏁 Next click failed — done")
                    break
        finally:
            await page.close()
        
        return all_data
    
    async def _scrape_load_more(self) -> List[Dict]:
        cfg = self.config
        selector = cfg.load_more_selector
        all_data: List[Dict] = []
        click_count = 0
        max_clicks = cfg.max_pages or 200
        no_new = 0
        
        page = await self._context.new_page()
        try:
            await page.goto(
                self._build_page_url(1),
                wait_until="domcontentloaded", timeout=45_000,
            )
            await asyncio.sleep(2)
            
            while click_count < max_clicks:
                await self._scroll_down(page, times=2)
                
                data = await self._extract_from_page(page)
                for item in data:
                    item["page"] = click_count + 1
                
                new = self._dedup(data)
                if new:
                    all_data.extend(new)
                    no_new = 0
                    logger.info(f"   ✅ Click {click_count}: +{len(new)} (total {len(all_data)})")
                    self._save_csv(all_data, temp=True)
                else:
                    no_new += 1
                    if no_new >= 3:
                        logger.info("   🏁 No new data 3× — done")
                        break
                
                btn = page.locator(selector).first
                try:
                    if await btn.count() == 0 or not await btn.is_visible():
                        logger.info("   🏁 Load-more gone — done")
                        break
                    await btn.scroll_into_view_if_needed()
                    await btn.click()
                    click_count += 1
                    await asyncio.sleep(2 + random.random())
                except Exception:
                    logger.info("   🏁 Load-more failed — done")
                    break
        finally:
            await page.close()
        
        return all_data
    
    async def _scrape_infinite_scroll(self) -> List[Dict]:
        all_data: List[Dict] = []
        scroll_count = 0
        max_scrolls = self.config.max_pages or 100
        no_new = 0
        
        page = await self._context.new_page()
        try:
            await page.goto(
                self._build_page_url(1),
                wait_until="domcontentloaded", timeout=45_000,
            )
            await asyncio.sleep(2)
            
            while scroll_count < max_scrolls:
                data = await self._extract_from_page(page)
                for item in data:
                    item["page"] = scroll_count + 1
                
                new = self._dedup(data)
                if new:
                    all_data.extend(new)
                    no_new = 0
                    logger.info(f"   ✅ Scroll {scroll_count}: +{len(new)} (total {len(all_data)})")
                    self._save_csv(all_data, temp=True)
                else:
                    no_new += 1
                    if no_new >= 5:
                        logger.info("   🏁 No new data 5 scrolls — done")
                        break
                
                prev_h = await page.evaluate("document.documentElement.scrollHeight")
                await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                scroll_count += 1
                await asyncio.sleep(2.5 + random.random())
                new_h = await page.evaluate("document.documentElement.scrollHeight")
                if new_h == prev_h:
                    no_new += 1
        finally:
            await page.close()
        
        return all_data
    
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    #  CSV Save
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    def _save_csv(self, data: List[Dict], temp: bool = False) -> Path:
        CSV_FOLDER.mkdir(parents=True, exist_ok=True)
        path = self.config.csv_temp_path if temp else self.config.csv_path
        
        fieldnames = ["no", "page", "title", "link", "thumbnail", "duration", "views"]
        rows = []
        for i, item in enumerate(data, 1):
            rows.append({
                "no": i,
                "page": item.get("page", ""),
                "title": item.get("title", ""),
                "link": item.get("link", ""),
                "thumbnail": item.get("thumbnail", ""),
                "duration": item.get("duration", ""),
                "views": item.get("views", ""),
            })
        
        with open(path, "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
        
        return path
    
    def _cleanup_temp(self):
        try:
            self.config.csv_temp_path.unlink(missing_ok=True)
        except Exception:
            pass
    
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    #  Main scrape()
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    async def scrape(self) -> List[Dict]:
        cfg = self.config
        ptype = cfg.pagination_type
        
        print(f"\n{'=' * 58}")
        print(f"🚀  CSV GETTER v3")
        print(f"{'=' * 58}")
        cfg.print_summary()
        print(f"{'─' * 58}")
        
        if ptype in ("numbered", "url_pattern"):
            total = await self._detect_total_pages()
            if cfg.max_pages:
                total = min(total, cfg.max_pages)
            print(f"\n📊 {total} pages detected")
            print(f"🔄 {cfg.concurrent} concurrent\n")
            all_data = await self._scrape_numbered(total)
        
        elif ptype == "next_button":
            print(f"\n➡️ Next-button: {cfg.next_button_selector}\n")
            all_data = await self._scrape_click_next()
        
        elif ptype == "load_more":
            print(f"\n📥 Load-more: {cfg.load_more_selector}\n")
            all_data = await self._scrape_load_more()
        
        elif ptype == "infinite_scroll":
            print(f"\n♾️ Infinite scroll\n")
            all_data = await self._scrape_infinite_scroll()
        
        else:
            print(f"\n⚠️ Unknown type '{ptype}' — trying single page\n")
            _, data = await self._scrape_single_page(1)
            all_data = self._dedup(data)
        
        all_data.sort(key=lambda x: x.get("page", 0))
        final_path = self._save_csv(all_data, temp=False)
        self._cleanup_temp()
        
        print(f"\n{'=' * 58}")
        print(f"🎉  DONE!")
        print(f"{'─' * 58}")
        print(f"   Total videos: {len(all_data)}")
        print(f"   Saved to:     {final_path}")
        print(f"{'=' * 58}\n")
        
        return all_data


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  🎯 Main Entry Point
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


async def run(
    url: str,
    concurrent: int = DEFAULT_CONCURRENT,
    max_pages: int = 0,
    headless: bool = True,
    proxy: Optional[str] = None,
    force_scout: bool = False,
) -> List[Dict]:
    """
    Main entry point. Just give a URL.
    
    1. Check if adapter exists for this domain
    2. If not → run Scout → save adapter
    3. Load adapter → scrape → save CSV/{domain}.csv
    
    Args:
        url:          Target URL
        concurrent:   Parallel page fetches (for numbered pagination)
        max_pages:    Limit pages (0 = no limit)
        headless:     Browser headless mode
        proxy:        Optional proxy server
        force_scout:  Re-run scout even if adapter exists
    """
    domain = _url_to_domain(url)
    
    print(f"\n{'=' * 58}")
    print(f"🎯  CSV GETTER")
    print(f"{'=' * 58}")
    print(f"   URL:    {url}")
    print(f"   Domain: {domain}")
    
    # ── Step 1: Find or create adapter ──
    
    adapter_path = find_adapter_file(domain)
    
    if adapter_path and not force_scout:
        print(f"   ✅ Adapter found: {adapter_path}")
        config = SiteConfig.from_adapter_file(adapter_path, url)
    else:
        if force_scout:
            print(f"   🔄 Force re-scan requested")
        else:
            print(f"   ❌ No adapter for '{domain}'")
        
        print(f"\n{'─' * 58}")
        print(f"🔍  Running Scout to analyze site...")
        print(f"{'─' * 58}")
        
        # Import scout
        from .scout import CSVScout, print_report, generate_adapter_code
        
        async with CSVScout(proxy=proxy, headless=headless) as scout:
            analysis = await scout.analyze(url)
        
        print_report(analysis)
        
        if analysis.error:
            print(f"\n❌ Scout failed: {analysis.error}")
            return []
        
        if not analysis.is_valid:
            print("\n⚠️ Scout couldn't find valid selectors")
            print("   Run scout manually: python -m csv_getter.csv_scout <url>")
            return []
        
        # Save adapter file
        code = generate_adapter_code(analysis)
        ADAPTERS_FOLDER.mkdir(parents=True, exist_ok=True)
        adapter_path = ADAPTERS_FOLDER / f"{_domain_to_slug(domain)}.py"
        adapter_path.write_text(code, encoding="utf-8")
        print(f"\n💾 Adapter saved: {adapter_path}")
        
        # Load the config from what we just saved
        config = SiteConfig.from_adapter_file(adapter_path, url)
    
    # ── Step 2: Apply overrides ──
    
    config.concurrent = concurrent
    config.max_pages = max_pages
    
    # ── Step 3: Scrape ──
    
    print(f"\n{'─' * 58}")
    print(f"📥  Starting scrape...")
    print(f"{'─' * 58}")
    
    async with CSVGetter(config) as getter:
        data = await getter.scrape()
    
    return data


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  CLI  (python -m csv_getter.csv_getter <url>)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if __name__ == "__main__":
    import sys
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(message)s",
    )
    
    if len(sys.argv) < 2:
        print("Usage: python -m csv_getter.csv_getter <url> [max_pages] [concurrent]")
        print("Example: python -m csv_getter.csv_getter https://jable.tv/categories/chinese/ 10 5")
        sys.exit(1)
    
    target_url = sys.argv[1]
    max_pg = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    conc = int(sys.argv[3]) if len(sys.argv) > 3 else 5
    
    asyncio.run(run(target_url, concurrent=conc, max_pages=max_pg))